server:
  port: 8084
spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/miercoles


eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    enabled: false



