spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway-service:
            issuer-uri: http://localhost:8080/realms/miercoles
        registration:
          api-gateway-service:
            provider: api-gateway-service
            client-id:
            client-secret:
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9090/login/oauth2/code/keycloak'
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: users-service
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0
server:
  port: 9090