server:
  port: 8181

spring:
  application:
    name: keycloak-local-client

dh:
  keycloak:
#    es una forma diferente de configurar un client
    serverUrl: http://localhost:8080
    realm: reino
    clientId: keycloak-local-client
    clientSecret:
